apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec:
  # https://linuxhandbook.com/crontab/
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-pod
            image: ubuntu
            command: ["expr", "3", "+", "2"]
          restartPolicy: Never