apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ["expr", "3", "+", "2"]
      restartPolicy: Never