apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-host-path
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data