apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-map
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    envFrom:
      - configMapRef:
          name: app-config